#define MCAP_IMPLEMENTATION  // Define this in exactly one .cpp file
#include <mcap/writer.hpp>
#include <mcap/reader.hpp>

#include <iostream>
#include <vector>
#include <fstream>  // Required for std::ifstream
#include "vehicle_sim_generated.h"  // Generated by flatc

int WriteFile()
{
  // Initialize MCAP writer
  auto options = mcap::McapWriterOptions("");
  mcap::McapWriter writer;
  auto status = writer.open("vehicle_log.mcap", options);
  if (!status.ok()) {
    std::cerr << "Failed to open MCAP file: " << status.message << "\n";
    return 1;
  }

  // Register schema (read from .fbs file)
  std::string schema_definition;
  {
    std::ifstream fbs_file("vehicle_sim.fbs");
    schema_definition = std::string((std::istreambuf_iterator<char>(fbs_file)),
                                  std::istreambuf_iterator<char>());
  }
  mcap::Schema schema("VehicleState", "flatbuffer", schema_definition);
  writer.addSchema(schema);

  // Create channel
  mcap::Channel channel("vehicle_data", "flatbuffer", schema.id);
  writer.addChannel(channel);

  // Create sample vehicle data
  flatbuffers::FlatBufferBuilder builder;

  // Vehicle 1
  auto name1 = builder.CreateString("Tesla Model 3");
  auto vehicle1 = VehicleSim::CreateVehicleState(
    builder,
    1,              // id
    1234567890000,  // timestamp (ns)
    10.5f,          // x position
    20.3f,          // y position
    5.2f,           // speed
    1.1f,            // acceleration
    name1                   // vehicle_name
  );
  builder.Finish(vehicle1);

  // Write vehicle 1 to MCAP
  {
    mcap::Message msg;
    msg.channelId = channel.id;
    msg.sequence = 0;
    msg.publishTime = 1234567890000;
    msg.data = reinterpret_cast<const std::byte*>(builder.GetBufferPointer());
    msg.dataSize = builder.GetSize();
    auto res = writer.write(msg);
    if (!res.ok()) {
      std::cerr << "failed to write message: " << res.message << std::endl;
      writer.close();
      return 1;
    }
  }

  // Vehicle 2
  auto name2 = builder.CreateString("Ford Mustang");
  auto vehicle2 = VehicleSim::CreateVehicleState(
    builder,
    2,              // id
    1234567891000,  // timestamp (ns)
    15.2f,          // x position
    18.7f,          // y position
    3.8f,           // speed
    0.5f,            // acceleration
    name2                   // vehicle_name
  );
  builder.Finish(vehicle2);

  // Write vehicle 2 to MCAP
  {
    mcap::Message msg;
    msg.channelId = channel.id;
    msg.sequence = 1;
    msg.publishTime = 1234567891000;
    msg.data = reinterpret_cast<const std::byte*>(builder.GetBufferPointer());
    msg.dataSize = builder.GetSize();
    auto res = writer.write(msg);
    if (!res.ok()) {
      std::cerr << "failed to write message: " << res.message << std::endl;
      writer.close();
      return 1;
    }
  }

  // Close the file
  writer.close();
  std::cout << "Successfully logged 2 vehicle states to vehicle_log.mcap\n";

  return 0;
}

void printVehicle(const VehicleSim::VehicleState* vehicle) {
  std::cout << vehicle->vehicle_name()->c_str() << " (ID: " << vehicle->id() << ")\n"
            << "  Position: (" << vehicle->x() << ", " << vehicle->y() << ")\n"
            << "  Speed: " << vehicle->speed() << " m/s\n"
            << "  Acceleration: " << vehicle->acceleration() << " m/s²\n"
            << "  Timestamp: " << vehicle->timestamp() << "ns\n\n";
}

int ReadFile() {
  // 1. Initialize reader
  mcap::McapReader reader;
  auto status = reader.open("vehicle_log.mcap");
  if (!status.ok()) {
      std::cerr << "Failed to open file: " << status.message << "\n";
      return 1;
  }

  // 2. Read messages
  std::cout << "Reading MCAP file...\n";
  for (const auto& msg : reader.readMessages()) {
      // Verify schema matches
      if (msg.channel->messageEncoding != "flatbuffer") continue;

      // Deserialize FlatBuffer
      auto vehicle = VehicleSim::GetVehicleState(
          reinterpret_cast<const uint8_t*>(msg.message.data)
      );

      printVehicle(vehicle);
  }

  reader.close();
  return 0;
}

int main()
{
  std::cout << "MCAP Logger 0.1" << std::endl;
  WriteFile();
  ReadFile();
  std::cout << "Done!" << std::endl;
  return 0;
}