// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VEHICLESIM_VEHICLESIM_H_
#define FLATBUFFERS_GENERATED_VEHICLESIM_VEHICLESIM_H_

#include "flatbuffers/flatbuffers.h"

namespace VehicleSim {

struct VehicleStateSpeed;
struct VehicleStateSpeedBuilder;

struct VehicleStatePos;
struct VehicleStatePosBuilder;

struct VehicleStateSpeed FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef VehicleStateSpeedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SPEED = 4
  };
  float speed() const {
    return GetField<float>(VT_SPEED, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_SPEED) &&
           verifier.EndTable();
  }
};

struct VehicleStateSpeedBuilder {
  typedef VehicleStateSpeed Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_speed(float speed) {
    fbb_.AddElement<float>(VehicleStateSpeed::VT_SPEED, speed, 0.0f);
  }
  explicit VehicleStateSpeedBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<VehicleStateSpeed> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<VehicleStateSpeed>(end);
    return o;
  }
};

inline flatbuffers::Offset<VehicleStateSpeed> CreateVehicleStateSpeed(
    flatbuffers::FlatBufferBuilder &_fbb,
    float speed = 0.0f) {
  VehicleStateSpeedBuilder builder_(_fbb);
  builder_.add_speed(speed);
  return builder_.Finish();
}

struct VehicleStatePos FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef VehicleStatePosBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X) &&
           VerifyField<float>(verifier, VT_Y) &&
           verifier.EndTable();
  }
};

struct VehicleStatePosBuilder {
  typedef VehicleStatePos Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(VehicleStatePos::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(VehicleStatePos::VT_Y, y, 0.0f);
  }
  explicit VehicleStatePosBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<VehicleStatePos> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<VehicleStatePos>(end);
    return o;
  }
};

inline flatbuffers::Offset<VehicleStatePos> CreateVehicleStatePos(
    flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f) {
  VehicleStatePosBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

inline const VehicleSim::VehicleStatePos *GetVehicleStatePos(const void *buf) {
  return flatbuffers::GetRoot<VehicleSim::VehicleStatePos>(buf);
}

inline const VehicleSim::VehicleStatePos *GetSizePrefixedVehicleStatePos(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<VehicleSim::VehicleStatePos>(buf);
}

inline bool VerifyVehicleStatePosBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VehicleSim::VehicleStatePos>(nullptr);
}

inline bool VerifySizePrefixedVehicleStatePosBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VehicleSim::VehicleStatePos>(nullptr);
}

inline void FinishVehicleStatePosBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<VehicleSim::VehicleStatePos> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVehicleStatePosBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<VehicleSim::VehicleStatePos> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VehicleSim

#endif  // FLATBUFFERS_GENERATED_VEHICLESIM_VEHICLESIM_H_
