// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VEHICLESTATE_VEHICLESIM_H_
#define FLATBUFFERS_GENERATED_VEHICLESTATE_VEHICLESIM_H_

#include "flatbuffers/flatbuffers.h"

namespace VehicleSim {

struct VehicleState;
struct VehicleStateBuilder;

struct VehicleState FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef VehicleStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SPEED = 4,
    VT_X = 6,
    VT_Y = 8
  };
  float speed() const {
    return GetField<float>(VT_SPEED, 0.0f);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_SPEED) &&
           VerifyField<float>(verifier, VT_X) &&
           VerifyField<float>(verifier, VT_Y) &&
           verifier.EndTable();
  }
};

struct VehicleStateBuilder {
  typedef VehicleState Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_speed(float speed) {
    fbb_.AddElement<float>(VehicleState::VT_SPEED, speed, 0.0f);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(VehicleState::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(VehicleState::VT_Y, y, 0.0f);
  }
  explicit VehicleStateBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<VehicleState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<VehicleState>(end);
    return o;
  }
};

inline flatbuffers::Offset<VehicleState> CreateVehicleState(
    flatbuffers::FlatBufferBuilder &_fbb,
    float speed = 0.0f,
    float x = 0.0f,
    float y = 0.0f) {
  VehicleStateBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_speed(speed);
  return builder_.Finish();
}

inline const VehicleSim::VehicleState *GetVehicleState(const void *buf) {
  return flatbuffers::GetRoot<VehicleSim::VehicleState>(buf);
}

inline const VehicleSim::VehicleState *GetSizePrefixedVehicleState(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<VehicleSim::VehicleState>(buf);
}

inline bool VerifyVehicleStateBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VehicleSim::VehicleState>(nullptr);
}

inline bool VerifySizePrefixedVehicleStateBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VehicleSim::VehicleState>(nullptr);
}

inline void FinishVehicleStateBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<VehicleSim::VehicleState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVehicleStateBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<VehicleSim::VehicleState> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VehicleSim

#endif  // FLATBUFFERS_GENERATED_VEHICLESTATE_VEHICLESIM_H_
