// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VEHICLESIM_VEHICLESIM_H_
#define FLATBUFFERS_GENERATED_VEHICLESIM_VEHICLESIM_H_

#include "flatbuffers/flatbuffers.h"

namespace VehicleSim {

struct VehicleState;
struct VehicleStateBuilder;

struct VehicleState FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef VehicleStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TIMESTAMP = 6,
    VT_X = 8,
    VT_Y = 10,
    VT_SPEED = 12,
    VT_ACCELERATION = 14,
    VT_VEHICLE_NAME = 16
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float speed() const {
    return GetField<float>(VT_SPEED, 0.0f);
  }
  float acceleration() const {
    return GetField<float>(VT_ACCELERATION, 0.0f);
  }
  const flatbuffers::String *vehicle_name() const {
    return GetPointer<const flatbuffers::String *>(VT_VEHICLE_NAME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP) &&
           VerifyField<float>(verifier, VT_X) &&
           VerifyField<float>(verifier, VT_Y) &&
           VerifyField<float>(verifier, VT_SPEED) &&
           VerifyField<float>(verifier, VT_ACCELERATION) &&
           VerifyOffset(verifier, VT_VEHICLE_NAME) &&
           verifier.VerifyString(vehicle_name()) &&
           verifier.EndTable();
  }
};

struct VehicleStateBuilder {
  typedef VehicleState Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(VehicleState::VT_ID, id, 0);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(VehicleState::VT_TIMESTAMP, timestamp, 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(VehicleState::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(VehicleState::VT_Y, y, 0.0f);
  }
  void add_speed(float speed) {
    fbb_.AddElement<float>(VehicleState::VT_SPEED, speed, 0.0f);
  }
  void add_acceleration(float acceleration) {
    fbb_.AddElement<float>(VehicleState::VT_ACCELERATION, acceleration, 0.0f);
  }
  void add_vehicle_name(flatbuffers::Offset<flatbuffers::String> vehicle_name) {
    fbb_.AddOffset(VehicleState::VT_VEHICLE_NAME, vehicle_name);
  }
  explicit VehicleStateBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<VehicleState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<VehicleState>(end);
    return o;
  }
};

inline flatbuffers::Offset<VehicleState> CreateVehicleState(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    uint64_t timestamp = 0,
    float x = 0.0f,
    float y = 0.0f,
    float speed = 0.0f,
    float acceleration = 0.0f,
    flatbuffers::Offset<flatbuffers::String> vehicle_name = 0) {
  VehicleStateBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_id(id);
  builder_.add_vehicle_name(vehicle_name);
  builder_.add_acceleration(acceleration);
  builder_.add_speed(speed);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

inline flatbuffers::Offset<VehicleState> CreateVehicleStateDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    uint64_t timestamp = 0,
    float x = 0.0f,
    float y = 0.0f,
    float speed = 0.0f,
    float acceleration = 0.0f,
    const char *vehicle_name = nullptr) {
  auto vehicle_name__ = vehicle_name ? _fbb.CreateString(vehicle_name) : 0;
  return VehicleSim::CreateVehicleState(
      _fbb,
      id,
      timestamp,
      x,
      y,
      speed,
      acceleration,
      vehicle_name__);
}

inline const VehicleSim::VehicleState *GetVehicleState(const void *buf) {
  return flatbuffers::GetRoot<VehicleSim::VehicleState>(buf);
}

inline const VehicleSim::VehicleState *GetSizePrefixedVehicleState(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<VehicleSim::VehicleState>(buf);
}

inline bool VerifyVehicleStateBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VehicleSim::VehicleState>(nullptr);
}

inline bool VerifySizePrefixedVehicleStateBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VehicleSim::VehicleState>(nullptr);
}

inline void FinishVehicleStateBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<VehicleSim::VehicleState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVehicleStateBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<VehicleSim::VehicleState> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VehicleSim

#endif  // FLATBUFFERS_GENERATED_VEHICLESIM_VEHICLESIM_H_
